### ISSUE TITLE
Create additional file with more granular/refined data points

### ISSUE THREAD

**Issue by AminuBishir** [Kamparia/nigeria-covid19-data#1]
I think it will aid in creating more refined analysis if a file detailing individual report cases can be added. This file should contain cols like:
|state | case_type | counts | date | time |

**Comment by AminuBishir** [comment]
I'll like to work on this

**Comment by Kamparia** [comment]
Hi Aminu, thanks for your feedback. 

Having more granular data points will definitely help to produce more insights, the challenge is the availability and sourcing of the data. I am currently working with publicly available datasets.

If you have links or sources to these types of data points, please do not hesitate to share.

Thanks

**Comment by AminuBishir** [comment]
Of course I do Kamparia
I scraped the data from their Twitter handle. I've even compiled the csv now but I couldn't push my contribution due to accessibility issue. I committed the change on an new branch, you can add me as a contributor so I can push the change for further review and possible merger to the main branch.
Thanks

**Comment by AminuBishir** [comment]
This is the project I'm currently working on: https://aminubishir.github.io/covid-1_9/

**Comment by Kamparia** [comment]
The project is cool but I didn't see you make use of any data that is granular like what you said. 

Would be glad to add you as a contributor if you can provide more reliable data than what is on NCDC website or Twitter.

**Comment by AminuBishir** [comment]
Yeah as you  could have seen in the other project, the data are just being displayed without any further analysis.
The idea of gathering the covid19 data at a more granular level came to me yesterday and it's for the purpose of analysis (which I'm sure may be required later).
As per as information dissemination, regarding covid19 cases in Naija, is concerned no any other source can more official than NCDC's Twitter and website, and all the data have been extracted from there.
Thanks
